services:
  dashboard:
    image: arxiv_dashboard:latest
    env_file:
      - .env
    ports:
      - "8050:8050"
    volumes:
      - ./:/arxiv-2025
    networks:
      - dbnetwork
  
  postgres:
    image: postgres
    container_name: arxiv-2025-postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - arxiv-2025_postgresdata:/var/lib/postgresql/18/docker
    networks:
      - dbnetwork
  
volumes:
  arxiv-2025_postgresdata:
    external: true

networks:
  dbnetwork: 